# Project README

> Generated from `templates/README.md.tpl` using `muesli/readme-scribe` / `markscribe`.
>
> Edit this template, not the generated `README.md`.

## Overview

<!--
Replace this section with the purpose of your repo.
Example:
A CLI helper for learning Kubernetes/KIND workflows at work: pulling Docker images,
loading them into KIND, validating packages, and documenting useful Linux/Kubernetes commands.
-->

This repository contains tooling, notes, and experiments for learning and automating Kubernetes/KIND workflows.

## Current Focus

- Kubernetes fundamentals: Pods, Deployments, Services, ConfigMaps, Secrets, and volumes
- KIND image-loading workflows
- Bash automation with `&`, `wait`, `wait -n`, `printf`, and exit codes
- Work-safe documentation of repeatable infrastructure patterns

## Recent Progress

<!-- DEVLOG:START -->
{{- range recentContributions 10 }}
- [{{ .Repo.Name }}]({{ .Repo.URL }}) — {{ humanize .OccurredAt }}
{{- if .Repo.Description }}
  - {{ .Repo.Description }}
{{- end }}
{{- end }}
<!-- DEVLOG:END -->

## Recent Pull Requests

{{- range recentPullRequests 5 }}
- [{{ .Title }}]({{ .URL }}) — `{{ .State }}` on [{{ .Repo.Name }}]({{ .Repo.URL }}) · {{ humanize .CreatedAt }}
{{- end }}

## Useful Commands

### KIND

```bash
kind create cluster --name work-lab
kind get clusters
kind load docker-image nginx:latest --name work-lab
kubectl get pods -A
```

### Docker images

```bash
docker pull nginx:latest
docker pull busybox:latest
docker pull postgres:17
docker pull redis:8
```

### Bash worker pool pattern

```bash
images=(
  nginx:latest
  busybox:latest
  postgres:17
  redis:8
)

max_workers=4

for image in "${images[@]}"; do
  docker pull "$image" &

  while (( $(jobs -r | wc -l) >= max_workers )); do
    wait -n
  done
done

wait
```

### Package existence checks with DNF

```bash
if dnf info git &>/dev/null; then
  printf '%-20s %s\n' "git" "available"
else
  printf '%-20s %s\n' "git" "missing"
fi
```

## Learning Notes

### Bash concepts

- `command &` runs a command in the background.
- `wait` pauses until background jobs finish.
- `wait -n` pauses until one background job finishes.
- `&>/dev/null` suppresses both stdout and stderr.
- Bash `if` statements check command exit codes.

### Kubernetes concepts to document

- What is a Pod?
- What is a Deployment?
- What is a Service?
- What is a ConfigMap?
- What is a Secret?
- What is a PersistentVolumeClaim?
- How does KIND load local Docker images?

## Repository Activity

### Recently Created Repositories

{{- range recentRepos 5 }}
- [{{ .Name }}]({{ .URL }}){{ if .Description }} — {{ .Description }}{{ end }}
{{- end }}

### Recently Starred Repositories

{{- range recentStars 5 }}
- [{{ .Name }}]({{ .URL }}){{ if .Description }} — {{ .Description }}{{ end }}
{{- end }}

## TODO

- [ ] Add a first working KIND image-load command
- [ ] Add package validation
- [ ] Add parallel image pulling
- [ ] Add clearer progress output
- [ ] Add Kubernetes deployment examples
- [ ] Add troubleshooting notes

---

_Last generated by GitHub Actions using `readme-scribe`._
